% Created by: Isak Bohman, 2015
function test_gui
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

close all

f3 = figure('Visible','on','Position',[160,200,1600,800]);

p = uipanel('Title','Data creation',...
    'Position',[0.02 0.02 0.96 0.96]);

testdataload    = uicontrol('Style','pushbutton',...
    'String','Load test data', 'Units','normalized','Position',[0.5,0.44,0.2,0.05],...
    'Callback',@testdataload_callback, ...
    'Enable','off');

    function testdataload_callback(source,eventdata)
        
    end

launch_data_gui    = uicontrol('Style','pushbutton',...
    'String','Launch data creation GUI', 'Units','normalized','Position',[0.5,0.39,0.2,0.05],...
    'Callback',@launch_data_gui_callback);

    function launch_data_gui_callback(source,eventdata)
        GUI();
    end

testresultsave    = uicontrol('Style','pushbutton',...
    'String','Save test results', 'Units','normalized','Position',[0.05,0.2,0.2,0.05],...
    'Callback',@testresultsave_callback,'Enable','off');

    function testresultsave_callback(source,eventdata)
        
    end

run_tabu    = uicontrol('Style','pushbutton',...
    'String','Run tabu search', 'Units','normalized','Position',[0.05,0.05,0.2,0.05],...
    'Callback',@run_tabu_callback, ...
    'Enable','off');

    function run_tabu_callback(source,eventdata)
        
    end

run_lns    = uicontrol('Style','pushbutton',...
    'String','Run large neighborhood search', 'Units','normalized','Position',[0.05,0.1,0.2,0.05],...
    'Callback',@run_lns_callback, ...
    'Enable','off');

    function run_lns_callback(source,eventdata)
        
    end

run_lp    = uicontrol('Style','pushbutton',...
    'String','Run MIP method', 'Units','normalized','Position',[0.05,0.15,0.2,0.05],...
    'Callback',@run_lp_callback, ...
    'Enable','off');

    function run_lp_callback(source,eventdata)
        
    end

ha1 = axes('Units','pixels', 'Units','normalized','Position',[0.03,0.3,0.3,0.645], ...
    'Parent', p);

plot(1./(1:0.1:10));
title('Rate of convergence vs iterations');
xlabel('Number of iterations');
ylabel('Objective function');

level_selector = uibuttongroup(f3,'Title','Data difficulty level',...
    'Position',[.5 .5 .20 .08]);

levela = uicontrol(level_selector,'Style','radiobutton','String','Level A',...
    'Units','normalized',...
    'Position',[.1 .3 .6 .4], ...
    'Callback',@lv1_callback, ...
    'Tag', 'rab1');

    function lv1_callback(source,eventdata)
        
    end

levelb = uicontrol(level_selector,'Style','radiobutton','String','Level B',...
    'Units','normalized',...
    'Position',[.4 .3 .6 .4], ...
    'Callback',@lv2_callback, ...
    'Tag', 'rab1');

    function lv2_callback(source,eventdata)
        
    end

levelc = uicontrol(level_selector,'Style','radiobutton','String','Level C',...
    'Units','normalized',...
    'Position',[.7 .3 .6 .4], ...
    'Callback',@lv3_callback, ...
    'Tag', 'rab1');

    function lv3_callback(source,eventdata)
        
    end

htext4  = uicontrol('Style','text','String','Level A data', 'Units','normalized',...
    'Position',[0.32,0.25,0.10,0.03]);

htext5  = uicontrol('Style','text','String','Level B data', 'Units','normalized',...
    'Position',[0.55,0.25,0.10,0.03]);

htext6  = uicontrol('Style','text','String','Level C data', 'Units','normalized',...
    'Position',[0.78,0.25,0.10,0.03]);

lb1 = uicontrol(f3,'Style','listbox',...
                'String',{'Test data 1','Test data 2','Test data 3','Test data 4'},...
                'Units','normalized',...
                'Position',[0.28 0.05 0.2 0.2],'Value',1, ...
                'Enable','off');
            
lb2 = uicontrol(f3,'Style','listbox',...
                'String',{'Test data 1','Test data 2','Test data 3','Test data 4'},...
                'Units','normalized',...
                'Position',[0.5 0.05 0.2 0.2],'Value',1, ...
                'Enable','off');
            
lb3 = uicontrol(f3,'Style','listbox',...
                'String',{'Test data 1','Test data 2','Test data 3','Test data 4'},...
                'Units','normalized',...
                'Position',[0.72 0.05 0.2 0.2],'Value',1, ...
                'Enable','off');


end

